### ISSUE TITLE
Compatibility with Jira Data Center 8.5

### ISSUE THREAD

**Issue by dgodoyAtsistemas** [atlascommunity/jira-plugins-groovy#125]
Hi team,

We are going to migrate Jira server license to data center license, but this app isn't supported on data center according to hosting options in the Atlassian marketplace. Really, is this app supported on data center or not?

Thank you.

Regards,
Diego.

**Comment by dgodoyAtsistemas** [comment]
Hi team,

Any news about this question?

Regards,
Diego.

**Comment by dariarostshina** [comment]
Hello, you can use server version on jira data center. It works fine on DC.

**Comment by dgodoyAtsistemas** [comment]
Hi @dariarostshina, thanks for the feedback.
