### ISSUE TITLE
Impact of log4j vulnerability

### ISSUE THREAD

**Issue by dp-pfzr** [atlascommunity/jira-plugins-groovy#132]
Hi Team,
We are using Jira Data Centre version 8.13.13. We just want to know if the log4j vulnerability is applicable to your plugin "MyGroovy".
If yes then let us know when the patch version will be released ?
Please let us know at the earliest.
Thank You in advance

**Comment by dariarostshina** [comment]
Hello,

We are using log4j built in Jira. Therefore, our plugin is not susceptible to this attack.
