### ISSUE TITLE
Cannot update to 1.18.0-jira8

### ISSUE THREAD

**Issue by Alexsergio** [atlascommunity/jira-plugins-groovy#15]
I'm trying to update groovy 

![image](https://user-images.githubusercontent.com/49282647/55567094-4bcdbd80-56fd-11e9-9369-c5944ec707c5.png)

but after installation i'm receiving incopatigle version

![image](https://user-images.githubusercontent.com/49282647/55567220-846d9700-56fd-11e9-9665-b6e38610b02d.png)

i tried also to download new groovy version 

![image](https://user-images.githubusercontent.com/49282647/55567363-cac2f600-56fd-11e9-9d0e-c7553ae9937f.png)

but i'm receiving this message 

![image](https://user-images.githubusercontent.com/49282647/55567402-e0382000-56fd-11e9-8f93-7fd91b229d68.png)

How can I solve?
This error prevent me to update to jira 8

**Comment by lexek** [comment]
Which exact version of jira 8 do you use?

As a workaround, uninstall and then install app.

**Comment by Alexsergio** [comment]
Jira Core 8.0.2
JIRA Service Desk 4.0.2
Jira software 8.0.2

speaking of workaround on uninstall will I lost all my script and configuration?

**Comment by lexek** [comment]
No data will be lost. Upgrade is basically doing the same thing.

**Comment by Alexsergio** [comment]
I tried on stage and it worked, no data lost thanks
