### ISSUE TITLE
Do the builtin JQL functions work?

### ISSUE THREAD

**Issue by lifei** [atlascommunity/jira-plugins-groovy#6]
I have seen the following code:

```java
    @Nonnull
    @Override
    public List<QueryLiteral> getValues(@Nonnull QueryCreationContext queryCreationContext, @Nonnull FunctionOperand functionOperand, @Nonnull TerminalClause terminalClause) {
        return ImmutableList.of();
    }
```

so it does not work, am i right?

**Comment by lexek** [comment]
Hi, they do work.
Function likely implements ClauseQueryFactory, which produces lucene query instead of QueryLiterals.
Keep in mind that build-in function names are prefixed with "my_".

**Comment by hustx3** [comment]
Many useful JQL functions like "issuesInEpics" are implemented in the library. Is there a guiding for how to use it in Jira. Now I cannot use it in Jira advanced search.

**Comment by lifei** [comment]
What's the correct way to write the following JQL of `issue in my_issuesInEpics("issue = LKRQ-3236")`? It's no error but does not work in expectation.

**Comment by lexek** [comment]
@lifei you might need to re-index your Jira instance to use functions that are related to issue links (including epics and sub-tasks).

**Comment by jan-zajic** [comment]
I have same experience. Jira was reindexed many times after we installed plugin. When i for example specify invalid link type:
`issue in my_hasLinks("a")` it correctly write "Unable to find link type with name "a"" on screen. But if i specify valid search, for example `issue in my_hasLinks()` or `issue in my_hasComments()` i get "No issues were found to match your search" everytime. Jira Core 7.13.0. Can you imagine the production Jira instance where there is no comment on any ticket? 😊

**Comment by lexek** [comment]
I think, I know what the issue is.
Can you try searching like “groovyFunction in ...” instead of “issue in ...”
Monday, 25 February 2019, 21:38 +0300 from notifications@github.com  <notifications@github.com>:

**Comment by jan-zajic** [comment]
@lexek  It works like a charm! Thank you very much.

**Comment by lifei** [comment]
Thank you very much! I'll try it soon.
